### ISSUE TITLE
FedACHdir was replaced with a 404 page

### ISSUE THREAD

**Issue by parsnips** [gatepay/FedACHdir#1]
That doesnt seem intentional https://github.com/gatepay/FedACHdir/commit/29c423f9fb952995baf406cc2a28625720e372d0

**Comment by williamkapke** [comment]
Thanks for the heads up! No- that's certainly not wanted.

It is fixed now :+1:

**Comment by parsnips** [comment]
@williamkapke  https://www.fededirectory.frb.org/FedACHdir.txt also 404's is this no longer going to be updated there?

**Comment by parsnips** [comment]
I'm assuming this repo is a mirror of that directory. It looks like the feds got a new location for this data complete with a TOS interstitial :(

https://www.frbservices.org/EPaymentsDirectory/FedACHdir.txt

**Comment by williamkapke** [comment]
Yeah they moved it. My update script now "agrees" to the TOS and then downloads. 
It looks like its still happy & updating today :)

I updated the README on this repo to mention the new location.
